stages:
  - build
  - deploy

variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  IMAGE_TAG: latest

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CONTAINER_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CONTAINER_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG .
    - docker push $CONTAINER_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY $VM_USER@$VM_IP 'docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CONTAINER_REGISTRY && docker pull $CONTAINER_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG && docker run -d -p 8080:8080 $CONTAINER_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG && docker rmi $CONTAINER_REGISTRY/$CI_PROJECT_PATH:$IMAGE_TAG'
  only:
    - main