echo "NODE_ENV=${NODE_ENV}" > .env

cat <<EOF >> .env
APP_NAME="${APP_NAME}"
APP_DESCRIPTION="${APP_DESCRIPTION}"
API_VERSION=${API_VERSION}
HOST=${HOST}
PORT=${PORT}
DB_CONNECTION=${DB_CONNECTION}
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}
DB_DATABASE=${DB_DATABASE}
MAIL_HOST="${MAIL_HOST}"
MAIL_USER=${MAIL_USER}
MAIL_PASSWORD=${MAIL_PASSWORD}
MAIL_FROM=${MAIL_FROM}
SECRET_KEY_CONFIRM=${SECRET_KEY_CONFIRM}
SECRET_KEY_FORGOT_PASSWORD=${SECRET_KEY_FORGOT_PASSWORD}
SECRET_KEY=${SECRET_KEY}
JWT_EXPIRE=${JWT_EXPIRE}
FRONTEND_URL=${FRONTEND_URL}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
FACEBOOK_CALLBACK_URL=${FACEBOOK_CALLBACK_URL}
EOF

echo "Environment variables set up successfully."